server:
  port: 8888

spring:
  application:
    name: tradex-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
       native:
          searchLocations: file:///${user.dir}/config-repo

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
